runtime: python39

# App Engine instance class (F1 is the free tier)
instance_class: F1

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 10

# Required for PubSub push subscription
inbound_services:
- warmup

# Handler configuration
handlers:
- url: /.*
  script: auto
  secure: always

# Environment variables
env_variables:
  PORT: "8080"

# Resources limits for free tier
resources:
  cpu: 1
  memory_gb: 0.25
  disk_size_gb: 0.5

# Entrypoint (adjust if needed)
entrypoint: gunicorn -b :$PORT -w 1 webhook_handler:app

# Liveness check
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 5 