   app = "summarizer"  # You'll replace this during fly launch
   primary_region = "iad"  # Choose a region close to your users
   
   [build]
   
   [http_service]
   internal_port = 8081
   force_https = true
   auto_stop_machines = true
   auto_start_machines = true
   min_machines_running = 1
   processes = ["app"]
   
   [[vm]]
   cpu_kind = "shared"
   cpus = 1
   memory_mb = 256