name: Bot Runner

on:
  workflow_run:
    workflows: ["Docker CI/CD"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      run_mode:
        description: 'Bot run mode'
        required: true
        default: 'normal'
        type: choice
        options:
          - normal
          - debug
          - test

env:
  REGISTRY: ghcr.io
  REPO_NAME: guardianangelww/summarizer4

jobs:
  run-bot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Print Run Info
        run: |
          echo "Run started by: ${{ github.actor }}"
          echo "Run date: $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "Run mode: ${{ github.event.inputs.run_mode || 'normal' }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest image
        run: docker pull ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest

      - name: Create log directory
        run: mkdir -p logs

      - name: Run bot container
        run: |
          docker run -d \
            --name telegram-bot \
            -v ${{ github.workspace }}/logs:/app/logs \
            -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
            -e ADMIN_USER_IDS=${{ secrets.ADMIN_USER_IDS }} \
            ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest

      - name: Wait for bot to start
        run: sleep 30

      - name: Check container status
        run: docker ps -a

      - name: Display initial logs
        run: docker logs telegram-bot

      - name: Monitor bot logs
        run: |
          echo "Starting log monitoring..."
          docker logs -f telegram-bot &
          PID=$!
          sleep 300  # Monitor for 5 minutes
          kill $PID

      - name: Upload log files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bot-logs-${{ github.run_number }}
          path: logs/
          retention-days: 5

      - name: Check bot health
        run: |
          HEALTH_STATUS=$(curl -s http://localhost:8080/health | jq -r .status)
          echo "Bot health status: $HEALTH_STATUS"
          if [ "$HEALTH_STATUS" != "healthy" ]; then
            echo "Bot is not healthy!"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          docker stop telegram-bot || true
          docker rm telegram-bot || true
